apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-init-argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/sw360cab/git-ops-init.git
    path: infra/kustomize/overlays/test
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true 