apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: git-ops-init
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: gitops-init-argocd
      useAnnotations: true